name: Deploy Static Build
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Add API endpoint
        run: echo "VITE_BASE_URL=${{ vars.API_DOMAIN }}" > .env

      - name: Build asset
        run: npm install && npm run build

      - uses: keithweaver/aws-s3-github-action@v1.0.0
        name: Copy build
        with:
          command: cp
          source: ./dist
          destination: s3://${{ vars.AWS_BUCKET_NAME }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ vars.AWS_REGION }}
          flags: --recursive

      - name: Finish
        run: echo "Website is available at ${{ vars.PUBLIC_URL }}"
